name: Output Information
on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: echo "The context of the workflow is ${{ toJSON(github) }}"